# Generated by Django 6.0 on 2025-12-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramydal_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='datasetrow',
            name='pyramydal_c_dataset_e73e2c_idx',
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pyramydal_core.dataset'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pyramydal_core.datasetversion'),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='version',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pyramydal_core.datasetversion'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='datasetrow',
            index=models.Index(fields=['version', 'row_index'], name='pyramydal_c_version_0e98d9_idx'),
        ),
        migrations.RemoveField(
            model_name='datasetrow',
            name='dataset',
        ),
        migrations.AlterUniqueTogether(
            name='datasetversion',
            unique_together={('dataset', 'version_number')},
        ),
    ]
